apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
spec:
  selector:
    matchLabels:
      app: pgadmin4
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      containers:
      - name: pgadmin4
        image: dpage/pgadmin4:latest
        imagePullPolicy: Always
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@example.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "admin"
        - name: PGADMIN_LISTEN_PORT
          value: "5050"
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin4-service
spec:
  type: ClusterIP
  selector:
    app: pgadmin4
  ports:
  - name: pgadmin4-port
    port: 5050
    targetPort: 5050
