apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-16-opt-pvc
  namespace: odoo-16
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-hostpath
