kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "db"
  namespace: odoo-16 # client namespace
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "16"
  numberOfInstances: 2
  enableConnectionPooler: true
  enableLogicalBackup: false
  volume:
    size: "25Gi"
    storageClass: "longhorn"
  users:
    odoo:
    - inherit
    - login
    - createdb
    rosen.vladimirov:
    - superuser
    - login

  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 1000m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 100Mi
