apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: 2024-04-19T10:27:03Z
  labels:
    application: spilo
    cluster-name: odoo-16
    team: acid
  name: odoo.odoo-16.credentials.postgresql.acid.zalan.do
  namespace: default
data:
  password: U1daclR6eXZuWFNRZWp1OE96dlV1NHhUN20zak1VZUtwMVBKM3NsdkpWOGRMQ3kxZUg1ZzY5ZUpuZHhIU2NVRA==
  username: b2Rvbw==
